all: part1 part2
part1: part1.c slow_functions.h slow_functions.c
	gcc part1.c slow_functions.c -std=c99 -pthread -o PART1

part2: part2.c slow_functions.h slow_functions.c
	gcc part2.c slow_functions.c -std=c99 -pthread -o PART2